services:
  # Reference PHP service to show how to link with OpenSign
  ossmb-php:
    image: php:8.3-cli-alpine
    container_name: ossmb-php
    working_dir: /app
    command: tail -f /dev/null
    env_file:
      - .env.dist
    volumes:
      - ./:/app
    networks:
      - ossmb-net

  ossmb-minio:
    image: quay.io/minio/minio
    container_name: ossmb-minio
    environment:
      MINIO_ENDPOINT: "http://localhost:9000"
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    ports:
      - "9006:9001"  # console Web UI
      - "9005:9000"  # S3 API
    networks:
      ossmb-net:
        aliases:
          - minio
          - ossmb.minio # Critical for virtual hosting style
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-init:
    image: quay.io/minio/minio
    container_name: ossmb-minio-init
    depends_on:
      ossmb-minio:
        condition: service_healthy
    networks:
      - ossmb-net
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 admin admin123;
      mc mb myminio/osmb --ignore-existing;
      mc admin user add myminio PejF8wMFAWF05hvteQqZ PeC2LtCO38Noenh6w1JCpcjiZPj31sQBfBwpgIij || true;
      mc admin policy attach myminio readwrite --user PejF8wMFAWF05hvteQqZ || true;
      exit 0;
      "

  ossmb-mongodb:
    image: mongo:8.2.5
    container_name: ossmb-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongodb_data:/data/db
    networks:
      - ossmb-net

  opensign:
    image: opensign/opensignserver:main
    container_name: ossmb-opensign
    ports:
      - "3005:3000"
    volumes:
      - ./resources/scripts/opensign-minio-patch.js:/usr/src/app/index.js
    environment:
      NODE_ENV: development
      PORT: "3000"
      USE_LOCAL: "false"
      APP_ID: opensign-dev-app-id
      MASTER_KEY: opensign-dev-master-key
      SERVER_URL: http://opensign:3000/app
      PUBLIC_SERVER_URL: http://localhost:3000/app
      DATABASE_URI: mongodb://root:rootpass@ossmb-mongodb:27017/opensign?authSource=admin
      MONGODB_URI: mongodb://root:rootpass@ossmb-mongodb:27017/opensign?authSource=admin
      DO_ENDPOINT: http://minio:9000
      DO_SPACE: osmb
      DO_BASEURL: http://localhost:9000/osmb
      DO_REGION: us-east-1
      DO_ACCESS_KEY_ID: PejF8wMFAWF05hvteQqZ
      DO_SECRET_ACCESS_KEY: PeC2LtCO38Noenh6w1JCpcjiZPj31sQBfBwpgIij
    depends_on:
      - ossmb-mongodb
      - ossmb-minio
    networks:
      - ossmb-net

networks:
  ossmb-net:

volumes:
  minio_data:
  mongodb_data:
