services:
  _defaults:
    autoconfigure: true

  Ossm\OssmBridgeBundle\Controller\:
    resource: "../src/Controller"
    tags: ["controller.service_arguments"]

  # OpenSign API Client
  Ossm\OssmBridgeBundle\Service\OpenSignService:
    arguments:
      $client: '@GuzzleHttp\Client'
      $appId: "%ossm_bridge.opensign.app_id%"
      $masterKey: "%ossm_bridge.opensign.master_key%"
      $apiUrl: "%ossm_bridge.opensign.api_url%"
      $userId: "%ossm_bridge.opensign.user_id%"
      $sessionToken: "%ossm_bridge.opensign.session_token%"

  Ossm\OssmBridgeBundle\Command\OpenSignSetupCommand:
    public: true
    arguments:
      $rootPath: "%kernel.project_dir%"
      $client: '@GuzzleHttp\Client'
      $appId: "%ossm_bridge.opensign.app_id%"
      $masterKey: "%ossm_bridge.opensign.master_key%"
      $apiUrl: "%ossm_bridge.opensign.api_url%"
    tags:
      - { name: "console.command", command: "ossmb:opensign:setup" }

  Ossm\OssmBridgeBundle\Command\InstallCommand:
    public: true
    arguments:
      $rootPath: "%kernel.project_dir%"
    tags:
      - { name: "console.command", command: "ossmb:install" }

  GuzzleHttp\Client: ~
