services:
  _defaults:
    autoconfigure: true
    autowire: true

  Mosl\OpenSignBridgeBundle\Controller\:
    resource: "../src/Controller"
    tags: ["controller.service_arguments"]

  Mosl\OpenSignBridgeBundle\Controller\WebhookController:
    arguments:
      $webhookSecret: "%opensign_bridge.webhook_secret%"

  # OpenSign API Client
  Mosl\OpenSignBridgeBundle\Service\OpenSignService:
    arguments:
      $client: '@GuzzleHttp\Client'
      $appId: "%opensign_bridge.opensign.app_id%"
      $masterKey: "%opensign_bridge.opensign.master_key%"
      $apiUrl: "%opensign_bridge.opensign.api_url%"
      $userId: "%opensign_bridge.opensign.user_id%"
      $sessionToken: "%opensign_bridge.opensign.session_token%"

  Mosl\OpenSignBridgeBundle\Command\OpenSignSetupCommand:
    public: true
    arguments:
      $rootPath: "%kernel.project_dir%"
      $client: '@GuzzleHttp\Client'
      $appId: "%opensign_bridge.opensign.app_id%"
      $masterKey: "%opensign_bridge.opensign.master_key%"
      $apiUrl: "%opensign_bridge.opensign.api_url%"
    tags:
      - { name: "console.command", command: "opensignb:opensign:setup" }

  Mosl\OpenSignBridgeBundle\Command\InstallCommand:
    public: true
    arguments:
      $rootPath: "%kernel.project_dir%"
    tags:
      - { name: "console.command", command: "opensignb:install" }

  GuzzleHttp\Client: ~
